Repository wp-cli/config-command, pull requests merged in 2019-04, with the labels that each got.

#85 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#87 Enhancement: Add PHP 7.3 to Travis CI build matrix
  .travis.yml
Labels: scope:testing

#89 Implement CS checking based on the `WP_CLI_CS` ruleset
  .distignore
  .gitignore
  composer.json
  config-command.php
  phpcs.xml.dist
  src/Config_Command.php
Labels: command:config

#88 Update template based on latest version
  templates/wp-config.mustache
Labels: command:config-create

#90 Update README.md file
  README.md
Labels: scope:documentation
