Repository wp-cli/config-command, pull requests merged in 2021-12, with the labels that each got.

#135 Add php 8.1 support
  composer.json
Labels: scope:distribution

#136 Document special `EOF` anchor
  src/Config_Command.php
Labels: scope:documentation

#102 #98 Add `dotenv` format option to `config get` command
  README.md
  features/config-list.feature
  src/Config_Command.php
Labels: command:config-list
